In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('C:\\Users\\abhir\\OneDrive\\Desktop\\Data Science using Python\\fraud_data.csv')
df

V1        V2        V3        V4        V5        V6        V7  \
0      1.176563  0.323798  0.536927  1.047002 -0.368652 -0.728586  0.084678   
1      0.681109 -3.934776 -3.801827 -1.147468 -0.735540 -0.501097  1.038865   
2      1.140729  0.453484  0.247010  2.383132  0.343287  0.432804  0.093380   
3     -1.107073 -3.298902 -0.184092 -1.795744  2.137564 -1.684992 -2.015606   
4     -0.314818  0.866839 -0.124577 -0.627638  2.651762  3.428128  0.194637   
...         ...       ...       ...       ...       ...       ...       ...   
21688 -3.959670  3.297819 -1.079436 -2.290106 -1.405133  2.452586 -4.649235   
21689 -1.066503  0.539240  0.735343 -0.506800  0.843980 -1.047877  1.141302   
21690 -2.175162 -0.441681  1.883137 -0.267440  1.056972  0.136404  0.113595   
21691  0.031406  0.694817  0.083233 -0.797912  0.564318 -0.560787  0.805901   
21692 -0.312369  0.944738  1.430605  0.627951  0.317725 -0.180406  0.793108   

              V8        V9       V10  ...        V21       V22       V23  \
0      -0.069246 -0.266389  0.155315  ...  -0.109627 -0.341365  0.057845   
1      -0.626979 -2.274423  1.527782  ...   0.652202  0.272684 -0.982151   
2       0.173310 -0.808999  0.775436  ...  -0.003802  0.058556 -0.121177   
3      -0.007181 -0.165760  0.869659  ...   0.130648  0.329445  0.927656   
4       0.670674 -0.442658  0.133499  ...  -0.312774 -0.799494 -0.064488   
...          ...       ...       ...  ...        ...       ...       ...   
21688 -12.365464  0.409493  1.251992  ...  12.617463 -2.969195  1.755050   
21689  -0.127448 -0.119221 -1.870265  ...  -0.162535 -0.576352 -0.184969   
21690  -0.055983  0.765616 -0.087568  ...  -0.201561  0.397761 -0.855500   
21691   0.051453 -0.053817 -0.200190  ...  -0.255891 -0.664635  0.018844   
21692  -0.104993 -0.493956  0.344477  ...   0.118417  0.609081 -0.270644   

            V24       V25       V26       V27       V28  Amount  Class  
0      0.499180  0.415211 -0.581949  0.015472  0.018065    4.67      0  
1      0.165900  0.360251  0.195321 -0.256273  0.056501  912.00      0  
2     -0.304215  0.645893  0.122600 -0.012115 -0.005945    1.00      0  
3     -0.049560 -1.892866 -0.575431  0.266573  0.414184   62.10      0  
4      0.953062 -0.429550  0.158225  0.076943 -0.015051    2.67      0  
...         ...       ...       ...       ...       ...     ...    ...  
21688  0.433324 -0.010827 -0.126613  0.200111 -0.160542   29.95      0  
21689 -0.136154  0.760012  0.048105 -0.017475  0.092365   85.66      0  
21690 -0.627900  0.590977  0.515065  0.433089 -0.150291  131.10      0  
21691 -0.539177 -0.504019  0.155133  0.232846  0.079420    4.49      0  
21692  0.004333 -0.114185 -0.287989  0.232375 -0.023563   14.90      0  

[21693 rows x 30 columns]

In [17]:
X,y=df.drop('Class',axis=1),df.Class
return (len(y[y==1])/(len(y[y==1])+len(y[y==0])))

0.016410823768035772

In [18]:
from sklearn.model_selection import train_test_split

df = pd.read_csv('C:\\Users\\abhir\\OneDrive\\Desktop\\Data Science using Python\\fraud_data.csv')

X = df.iloc[:,:-1]
y = df.iloc[:,-1]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [20]:
y

0        0
1        0
2        0
3        0
4        0
        ..
21688    0
21689    0
21690    0
21691    0
21692    0
Name: Class, Length: 21693, dtype: int64

In [23]:
from sklearn.dummy import DummyClassifier
from sklearn.metrics import recall_score,accuracy_score
dum=DummyClassifier(strategy='most_frequent').fit(X_train,y_train)
y_dummy_predictions=dum.predict(X_test)
acc_sc=accuracy_score(y_test,y_dummy_predictions)
rec_sc=recall_score(y_test,y_dummy_predictions)
print(acc_sc,rec_sc)


0.9852507374631269 0.0


In [24]:
dum.score(X_test,y_test)

0.9852507374631269

In [27]:
from sklearn.svm import SVC
from sklearn.metrics import recall_score,accuracy_score,precision_score
sv=SVC(C=1.0).fit(X_train,y_train)
y_predict=sv.predict(X_test)
acc_sc=accuracy_score(y_test,y_predict)
rec_sc=recall_score(y_test,y_predict)
pre_sc=precision_score(y_test,y_predict)
print (acc_sc,rec_sc,pre_sc)


C:\Users\abhir\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.9907817109144543 0.375 1.0


In [31]:
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

sv=SVC(C=1e9,gamma=1e-07).fit(X_train,y_train)
y_scores=sv.decision_function(X_test)>-220
clf=confusion_matrix(y_test,y_scores)
clf

array([[5320,   24],
       [  14,   66]], dtype=int64)

In [56]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import roc_curve,auc
import matplotlib.pyplot as plt
clf=LogisticRegression().fit(X_train,y_train)
y_proba=clf.predict_proba(X_test)
y_scores=clf.decision_function(X_test)
precision,recall,thresholds=precision_recall_curve(y_test,y_scores)
#plt.figure()
#plt.plot(precision,recall,label='Precision-Recall plot')
fpr_clf,tpr_clf,_=roc_curve(y_test,y_scores)
roc_auc_clf=auc(fpr_clf,tpr_clf)
#plt.figure()
#plt.plot(fpr_clf,tpr_clf,lw=3,label='AUC is : {:.2f}'.format(roc_auc_clf))
#plt.legend()

#recall[a]
#np.where(fpr_clf==0.16)
#fpr_clf





C:\Users\abhir\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.02456248, 0.0242629 , 0.02427035, ..., 1.        , 1.        ,
       1.        ])

In [67]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
logit=LogisticRegression()
grid_values={'penalty':['l1','l2'],'C':[0.01, 0.1, 1, 10, 100]}
grid_clf_rec=GridSearchCV(logit,param_grid=grid_values,scoring='recall')
grid_clf_rec.fit(X_train,y_train)
grid_clf_rec.cv_results_['mean_test_score'].reshape(5,2)


C:\Users\abhir\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\abhir\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\abhir\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\abhir\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\abhir\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to

array([[0.66666667, 0.76086957],
       [0.80072464, 0.80434783],
       [0.8115942 , 0.8115942 ],
       [0.80797101, 0.8115942 ],
       [0.80797101, 0.8115942 ]])